name: c100_resnet44_p0.01_multi_test3
mode: train
ckpt: null
dataset: cifar100
data_dir: ./data
num_gpus: 1
model: resnet44
loss: bce
clip: !!float 0.05
norm: batch
epochs: 160
batch_size: 128
lr: !!float 1e-1
wd: !!float 1e-4
optimizer: sgd
seed: 0
inject_p: !!float 0.01
inject_epoch: 10
comment: Powerlaw noise. ReLU6 in place of ReLU. All batchNorm + 1 GroupNorm before output layer.