name: c100_resnet32_p0.1_test1
mode: train
ckpt: null
dataset: cifar100
data_dir: ./data
num_gpus: 1
model: resnet32
loss: bce
epochs: 160
batch_size: 128
lr: !!float 1e-1
wd: !!float 1e-4
optimizer: sgd
seed: 0
inject_p: !!float 0.1
comment: null