name: c100_resnet44_evaluation
mode: evaluation
ckpt: c100_resnet44_base-epoch=157-val_acc=0.66.ckpt
dataset: cifar100
data_dir: ./data
num_gpus: 1
model: resnet44
loss: bce
epochs: 160
batch_size: 128
lr: !!float 1e-1
wd: !!float 1e-4
optimizer: sgd
seed: 0
inject_p: !!float 0.1
comment: null